(()=>{const switches=[...document.querySelectorAll('[data-language]')];const query=new URLSearchParams(location.search).get('lang');let lang=query==='en'||query==='pt'?query:(localStorage.getItem('papoa-language')||'pt');const translations={
'DESAFIO':'CHALLENGE','ABORDAGEM':'APPROACH','Anterior':'Previous','Próximo':'Next','Visualização 3D':'3D Visualisation','Contacto':'Contact','Privacidade':'Privacy','Voltar ao contacto':'Back to contact','Ver portfólio':'View projects','Mensagem enviada':'Message sent','Obrigado pelo contacto.':'Thank you for getting in touch.','Recebemos o seu pedido.':'We have received your enquiry.','Responderemos através dos contactos indicados.':'We will reply using the contact details provided.',
'Reabilitação':'Renovation','Projecto residencial':'Residential project','Moradia':'House',
'Actualizar uma moradia tradicional sem perder a leitura do existente.':'Update a traditional house while preserving its original character.',
'Trabalhar a relação entre a arquitectura existente, a madeira e a luz natural, criando interiores mais contemporâneos.':'Connect the existing architecture, timber and natural light to create more contemporary interiors.',
'Reabilitação de uma moradia tradicional, com uma leitura contemporânea dos espaços interiores e uma relação próxima entre a arquitectura existente, a madeira e a luz natural.':'Renovation of a traditional house, with a contemporary reading of its interiors and a close relationship between the existing architecture, timber and natural light.',
'Actualizar os espaços interiores sem perder a linguagem tradicional da moradia.':'Update the interiors while preserving the traditional language of the house.',
'Preservar a identidade exterior e introduzir interiores mais claros, contínuos e funcionais.':'Preserve the exterior identity and introduce brighter, more fluid and functional interiors.',
'Reabilitação de uma moradia de linguagem tradicional portuguesa, procurando preservar a identidade do volume existente e introduzir espaços interiores mais claros, contínuos e funcionais.':'Renovation of a house with a traditional Portuguese language, preserving the identity of the existing volume while introducing brighter, more fluid and functional interiors.',
'Criar uma moradia contemporânea luminosa e aberta ao jardim, mantendo privacidade.':'Create a bright contemporary house open to the garden while preserving privacy.',
'Trabalhar uma volumetria horizontal, coberturas planas e vãos amplos para ligar interior e exterior.':'Use horizontal volumes, flat roofs and generous openings to connect indoors and outdoors.',
'Moradia contemporânea em Geraldes, Peniche de linguagem arquitectónica depurada e volumetria horizontal, com coberturas planas e vãos amplos, pensada para maximizar a entrada de luz natural, garantir privacidade e criar uma relação directa entre os espaços interiores e o jardim envolvente.':'A contemporary house in Geraldes, Peniche, with a refined architectural language and horizontal volumes. Flat roofs and generous openings maximise natural light, preserve privacy and connect the interiors with the surrounding garden.',
'Organizar volumes, pátios e grandes vãos sem perder privacidade e coerência.':'Organise volumes, courtyards and generous openings while preserving privacy and coherence.',
'Usar a luz e a relação entre interior e exterior como elementos estruturantes da composição.':'Use light and the connection between indoors and outdoors as structuring elements.',
'Projecto residencial marcado por uma composição clara entre volumes, pátios e grandes vãos, onde a luz e a relação entre interior e exterior definem a experiência dos espaços.':'A residential project shaped by a clear composition of volumes, courtyards and generous openings, where light and the connection between indoors and outdoors define the experience.',
'Reabilitar a moradia preservando a memória da arquitectura tradicional.':'Renovate the house while preserving the memory of traditional architecture.',
'Reinterpretar a cobertura em telha cerâmica e articulá-la com novos volumes de linguagem contemporânea.':'Reinterpret the ceramic tiled roof and connect it with new volumes in a contemporary language.',
'Reabilitação habitacional na Serra d\'El-Rei, onde a arquitectura tradicional de cobertura em telha cerâmica é reinterpretada e articulada com novos volumes de linguagem contemporânea, criando uma frente urbana equilibrada entre memória construtiva, funcionalidade actual e uma leitura clara da intervenção.':'Residential renovation in Serra d\'El-Rei, reinterpreting traditional ceramic roof tiles alongside new contemporary volumes to create an urban frontage balancing built heritage, current function and a clear reading of the intervention.'
};
const reverse=Object.fromEntries(Object.entries(translations).map(([pt,en])=>[en,pt]));
const apply=next=>{lang=next;window.PAPOA_LANG=lang;document.documentElement.lang=lang==='en'?'en':'pt-PT';document.querySelectorAll('[data-pt][data-en]').forEach(el=>{if(el.tagName==='TITLE')document.title=el.dataset[lang];else el.textContent=el.dataset[lang];});
const dict=lang==='en'?translations:reverse;
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
while(walker.nextNode()){const node=walker.currentNode;if(node.parentElement.closest('[data-pt][data-en]'))continue;const raw=node.nodeValue;const trimmed=raw.trim();if(dict[trimmed])node.nodeValue=raw.replace(trimmed,dict[trimmed]);}
document.querySelectorAll('[placeholder]').forEach(el=>{const dictAttr=el.getAttribute('data-placeholder-'+lang);if(dictAttr)el.placeholder=dictAttr;});
window.dispatchEvent(new Event('papoa:languagechange'));document.querySelectorAll('[data-placeholder-pt][data-placeholder-en]').forEach(el=>el.placeholder=el.dataset['placeholder'+(lang==='en'?'En':'Pt')]);switches.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.language===lang)));localStorage.setItem('papoa-language',lang);};switches.forEach(button=>button.addEventListener('click',()=>{apply(button.dataset.language);const u=new URL(location.href);u.searchParams.set('lang',button.dataset.language);history.replaceState({},'',u);}));apply(lang);})();